apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.global.NameSpace }}
  labels:
    app: {{ .Chart.Name }}
  name: {{.Release.Name}}-webservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{.Release.Name}}-webservice
      imagePullSecrets:
        - name: buildatscaleregcred
      containers:
        - name: {{.Release.Name}}-webservice
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          # SCM specs
          - name: SCM_TYPE
            value: "{{ .Values.global.scm.type }}"
          - name: SCM_SERVICE_NAME
            value: "{{ .Release.Name }}-{{ .Values.global.scm.type }}"
          - name: SCM_PVC_NAME
            value: "{{ .Release.Name }}-{{ .Values.global.scm.type }}-pvc"
          # Jenkins specs
          - name: JENKINS_SERVICE_NAME
            value: "{{ .Release.Name }}-jenkins"
          - name: JENKINS_PVC_NAME
            value: "{{ .Release.Name }}-jenkins-pvc"
          # CouchDB specs
          - name: DATABASE_SERVICE_NAME
            value: "{{ .Release.Name }}-couchdb"
          - name: DATABASE_PVC_NAME
            value: "{{ .Release.Name }}-couchdb-pvc"
          # Artifactory specs
          - name: REGISTRY_SERVICE_NAME
            value: "{{ .Release.Name }}-{{ .Values.global.registry.type }}"
          - name: REGISTRY_PVC_NAME
            value: "{{ .Release.Name }}-{{ .Values.global.registry.type }}-pvc"
          - name: REGISTRY_TYPE
            value: "{{ .Values.global.registry.type }}"
          # Webservice specs
          - name: WEB_SERVICE_NAME
            value: "{{ .Release.Name }}-webservice"
          - name: WEB_PVC_NAME
            value: "{{ .Release.Name }}-webservice-pvc"
          # Kube specs
          - name: SERVICE_TYPE
            value: "{{ .Values.global.ServiceType }}"
          - name: KUBE_NAMESPACE
            value: "{{ .Values.global.NameSpace }}"
          - name: STORAGE_CLASS
            value: "{{ .Values.StorageClass }}"
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 6000
            name: debug
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 600
            failureThreshold: 600
            periodSeconds: 40
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 600
            periodSeconds: 40
            failureThreshold: 600
