{{- if eq .Values.global.scm.type "gitlab" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.global.NameSpace }}
  labels:
    app: {{ .Chart.Name }}
  name: {{.Release.Name}}-gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      hostname: {{ .Chart.Name }}
      containers:
        - name: {{.Release.Name}}-gitlab
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: GITLAB_ROOT_PASSWORD
            value: "{{ .Values.AdminPassword }}"
          volumeMounts:
          - name: {{.Release.Name}}-gitlab
            mountPath: /var/opt/gitlab
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 22
            name: ssh
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
            failureThreshold: 50
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 200
      volumes:
        - name: {{.Release.Name}}-gitlab
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: "{{ .Values.persistence.existingClaim}}"
            {{ else }}
            claimName: "{{.Release.Name}}-gitlab-pvc"
            {{- end -}}
{{- end -}}
